name: Feature Request
description: Suggest an enhancement or new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!
        
        **Before submitting:**
        - Check if this feature exists in [upstream](https://github.com/mrlt8/docker-wyze-bridge)
        - Search existing issues to avoid duplicates
        - Consider if this should be proposed to upstream first
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
  
  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: Where should this feature be implemented?
      options:
        - Fork-specific feature
        - Should be proposed to upstream
        - Documentation improvement
        - Unsure
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: |
        Describe your use case and how this feature would benefit you and others
        This helps prioritize features that benefit the community
  
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help test this feature
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
